name: deploy-infra

on: 
  push:
    branches:
      - main

jobs:
  deploy-infra:
    defaults:
      run:
        working-directory: ${{ vars.TF_ACTIONS_WORKING_DIR }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Terraform Init
      id: init
      run: terraform init -no-color -upgrade

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Terraform Apply
      run: | 
        terraform apply \
        -var="ingestion_repository_name=${{ vars.INGESTION_ECR_NAME }}" \
        -var="inference_repository_name=${{ vars.INFERENCE_ECR_NAME }}" \
        -var="memory_repository_name=${{ vars.MEMORY_ECR_NAME }}" \
        -var="list_collections_repository_name=${{ vars.LIST_COLLECTIONS_ECR_NAME }}" \
        -var="lex_router_repository_name=${{ vars.LEX_ROUTER_ECR_NAME }}" \
        -auto-approve -no-color -input=false 